# Rainfall Data Analysis Assignment (100 Marks, Due 6th July 2025)

You are provided with a rainfall dataset recording monthly measurements from various weather stations across different regions. The dataset includes rainfall (mm), number of rainy days, maximum and minimum temperatures, and whether the station is in an urban or rural area.

Dataset columns:

- `Region`: Name of the region (e.g., North, South, East, West)
- `Year`: Year of measurement
- `Month`: Month (e.g., Jan, Feb, ..., Dec)
- `Station`: Weather station name/ID (e.g., StationA, StationB)
- `Rainfall_mm`: Rainfall amount in millimeters
- `RainyDays`: Number of days in the month with rain
- `MaxTemp_C`: Maximum temperature recorded in that month (°C)
- `MinTemp_C`: Minimum temperature recorded in that month (°C)
- `UrbanRural`: "Urban" or "Rural"

## Part 1: Data Exploration ( 15 Marks)

1. Load the data into a pandas DataFrame. (2 Marks)
2. Display the first 5 rows of the DataFrame. (2 Marks)
3. Check for and handle any missing values. (6 Marks)
4. Provide summary statistics for all numeric columns. (5 Marks)

In [85]:
#Write your code here
import pandas as pd
df = pd.read_csv('Rainfall.csv', header = None)

In [86]:
#there is a problem in the dataset .csv as all datas are packed in one column
#so we need to split them manually
df = df[0].str.split(",", expand = True)
#expand = True is to expand it into dataframe columns

#reset again the column names follow the question given
df.columns = ['Region', 'Year', 'Month', 'Station', 'Rainfall_mm', 'RainyDays', 'MaxTemp_C', 'MinTemp_C', 'UrbanRural']

#remove the original unneat headers row
df = df[1:].reset_index(drop=True)

df.head()

,Region,Year,Month,Station,Rainfall_mm,RainyDays,MaxTemp_C,MinTemp_C,UrbanRural
0,North,2023,Jan,StationA,56.2,9,12.1,2.5,Urban
1,North,2023,Feb,StationA,72.1,12,14.7,3.0,Urban
2,North,2023,Jan,StationB,60.5,10,11.2,1.8,Rural
3,South,2023,Jan,StationC,81.0,13,19.6,7.2,Urban
4,South,2023,Feb,StationC,63.4,11,20.1,7.7,Urban

In [87]:
print("Missing value in each column:")
print(df.isnull().sum())

#if have missing value
df = df.dropna()

print("\nAfter Cleaning:")
print(df.isnull().sum())

Missing value in each column:
Region         0
Year           0
Month          0
Station        0
Rainfall_mm    0
RainyDays      0
MaxTemp_C      0
MinTemp_C      0
UrbanRural     0
dtype: int64

After Cleaning:
Region         0
Year           0
Month          0
Station        0
Rainfall_mm    0
RainyDays      0
MaxTemp_C      0
MinTemp_C      0
UrbanRural     0
dtype: int64

In [88]:
#convert columns from string to float/int
df['Year'] = df['Year'].astype(int)
df['Rainfall_mm'] = df['Rainfall_mm'].astype(float)
df['RainyDays'] = df['RainyDays'].astype(int)
df['MaxTemp_C'] = df['MaxTemp_C'].astype(float)
df['MinTemp_C'] = df['MinTemp_C'].astype(float)

df.describe()

         Year  Rainfall_mm  RainyDays  MaxTemp_C  MinTemp_C
count    10.0    10.000000   10.00000  10.000000  10.000000
mean   2023.0    66.160000   10.90000  16.100000   4.740000
std       0.0    12.154121    1.66333   2.982542   2.029888
min    2023.0    45.700000    8.00000  11.200000   1.800000
25%    2023.0    59.825000   10.00000  14.775000   3.050000
50%    2023.0    62.450000   11.00000  16.100000   5.100000
75%    2023.0    76.075000   12.00000  18.125000   6.050000
max    2023.0    84.200000   13.00000  20.100000   7.700000

## Part 2: Grouping and Aggregation (30 Marks)

1. For each **Station**, compute: (6 Marks)
    - Total rainfall 
    - Average number of rainy days 
    - Average maximum temperature 
    - Average minimum temperature

In [90]:
#Write your code here
station_summary = df['Rainfall_mm'].groupby(df['Station'])

#total rainfall
station_summary.sum()

Station
StationA    128.3
StationB    122.0
StationC    144.4
StationD    105.3
StationE    161.6
Name: Rainfall_mm, dtype: float64

In [91]:
station = df.groupby('Station').agg(total_rainfall = ('Rainfall_mm', 'sum'),
                                    avg_rainfall = ('RainyDays', 'mean'),
                                    max_temp = ('MaxTemp_C', 'mean'),
                                    min_temp = ('MinTemp_C', 'mean'))

station

          total_rainfall  avg_rainfall  max_temp  min_temp
Station
StationA           128.3          10.5     13.40      2.75
StationB           122.0          10.5     13.10      2.50
StationC           144.4          12.0     19.85      7.45
StationD           105.3           9.0     16.65      5.90
StationE           161.6          12.5     17.50      5.10

In [92]:
#Average number of rainy days
station_summary = df.groupby('Station')['RainyDays'].mean()
station_summary.sort_values(ascending = True, inplace = True)
print(station_summary)

Station
StationD     9.0
StationA    10.5
StationB    10.5
StationC    12.0
StationE    12.5
Name: RainyDays, dtype: float64

In [93]:
#Average maximum temperature
station_summary = df['MaxTemp_C'].groupby(df['Station'])

station_summary.mean()

Station
StationA    13.40
StationB    13.10
StationC    19.85
StationD    16.65
StationE    17.50
Name: MaxTemp_C, dtype: float64

In [94]:
#Average minimum temperature
station_summary = df['MinTemp_C'].groupby(df['Station'])

station_summary.mean()

Station
StationA    2.75
StationB    2.50
StationC    7.45
StationD    5.90
StationE    5.10
Name: MinTemp_C, dtype: float64

2. For each **Region & UrbanRural** combination, calculate: (6 Marks)
    - Average rainfall
    - Average maximum temperature
    - Average number of rainy days

In [96]:
#for Region adn UrbanRural combination
regionUrbanRural_summary = df['Rainfall_mm'].groupby([df['Region'], df['UrbanRural']])

#average rainfall
regionUrbanRural_summary.mean()

Region  UrbanRural
East    Rural         52.65
North   Rural         61.00
        Urban         64.15
South   Urban         72.20
West    Urban         80.80
Name: Rainfall_mm, dtype: float64

In [97]:
#average maximum temperature
regionUrbanRural_summary = df['MaxTemp_C'].groupby([df['Region'], df['UrbanRural']])

regionUrbanRural_summary.mean()

Region  UrbanRural
East    Rural         16.65
North   Rural         13.10
        Urban         13.40
South   Urban         19.85
West    Urban         17.50
Name: MaxTemp_C, dtype: float64

In [98]:
#average number of rainy days
regionUrbanRural_summary = df['RainyDays'].groupby([df['Region'], df['UrbanRural']])

regionUrbanRural_summary.mean()

Region  UrbanRural
East    Rural          9.0
North   Rural         10.5
        Urban         10.5
South   Urban         12.0
West    Urban         12.5
Name: RainyDays, dtype: float64

3. For each **Month** and **Region**, calculate: (6 Marks)
    - Total rainfall
    - Mean rainfall
    - Minimum and maximum rainfall

In [124]:
month_summary = df.groupby(['Month', 'Region']).agg(
    tot_rainfall = ('Rainfall_mm', 'sum'),
    mean_rainfall = ('Rainfall_mm', 'mean'),
    Min_Rainfall = ('Rainfall_mm','min'),
    Max_Rainfall = ('Rainfall_mm','max')
)

month_summary

              tot_rainfall  mean_rainfall  Min_Rainfall  Max_Rainfall
Month Region
Feb   East            59.6          59.60          59.6          59.6
      North           72.1          72.10          72.1          72.1
      South           63.4          63.40          63.4          63.4
      West            84.2          84.20          84.2          84.2
Jan   East            45.7          45.70          45.7          45.7
      North          116.7          58.35          56.2          60.5
      South           81.0          81.00          81.0          81.0
      West            77.4          77.40          77.4          77.4
Mar   North           61.5          61.50          61.5          61.5

In [100]:
#For Month 
month_summary = df['Rainfall_mm'].groupby(df['Month'])

#total rainfall
month_summary.sum()

Month
Feb    279.3
Jan    320.8
Mar     61.5
Name: Rainfall_mm, dtype: float64

In [101]:
#mean rainfall
month_summary = df['Rainfall_mm'].groupby(df['Month'])

month_summary.mean()

Month
Feb    69.825
Jan    64.160
Mar    61.500
Name: Rainfall_mm, dtype: float64

In [102]:
#Minimum and maximum rainfall
month_summary = df['Rainfall_mm'].groupby(df['Month'])

print("Minimum rainfall:")
print(month_summary.min())

print("\nMaximum rainfall:")
print(month_summary.max())

Minimum rainfall:
Month
Feb    59.6
Jan    45.7
Mar    61.5
Name: Rainfall_mm, dtype: float64

Maximum rainfall:
Month
Feb    84.2
Jan    81.0
Mar    61.5
Name: Rainfall_mm, dtype: float64

In [103]:
#For region
region_summary = df['Rainfall_mm'].groupby(df['Region'])

#total rainfall
region_summary.sum()

Region
East     105.3
North    250.3
South    144.4
West     161.6
Name: Rainfall_mm, dtype: float64

In [104]:
#mean rainfall
region_summary = df['Rainfall_mm'].groupby(df['Region'])

region_summary.mean()

Region
East     52.650
North    62.575
South    72.200
West     80.800
Name: Rainfall_mm, dtype: float64

In [105]:
region_summary = df['Rainfall_mm'].groupby(df['Region'])

print("Minimum rainfall:")
print(region_summary.min())

print("\nMaximum rainfall:")
print(region_summary.max())

Minimum rainfall:
Region
East     45.7
North    56.2
South    63.4
West     77.4
Name: Rainfall_mm, dtype: float64

Maximum rainfall:
Region
East     59.6
North    72.1
South    81.0
West     84.2
Name: Rainfall_mm, dtype: float64

4. Find the **Region and Month** with the highest recorded rainfall in the dataset. (4 Marks)

In [107]:
#Write your code here
max_rainfall_row = df.loc[df['Rainfall_mm'].idxmax()]
#to know the index of max value

region = max_rainfall_row['Region']
month = max_rainfall_row['Month']
amount = max_rainfall_row['Rainfall_mm']


print(f"Highest recorded rainfall was in {region}, during {month}: {amount} mm")

Highest recorded rainfall was in West, during Feb: 84.2 mm

5. For each **Year** and **UrbanRural** group, calculate: (4 Marks)
    - Average rainfall
    - Minimum rainfall
    - Maximum rainfall

In [116]:
year_summary = df.groupby(['Year','UrbanRural']).agg(
                average_rainfall = ('Rainfall_mm','mean'),
                min_rainfall = ('Rainfall_mm', 'min'),
                max_rainfall = ('Rainfall_mm', 'max'))
year_summary

                 average_rainfall  min_rainfall  max_rainfall
Year UrbanRural
2023 Rural              56.825000          45.7          61.5
     Urban              72.383333          56.2          84.2

In [ ]:
#Write your code here
#For year
year_summary = df['Rainfall_mm'].groupby(df['Year'])

#total rainfall
year_summary.mean()

In [ ]:
#min rainfall
year_summary = df['Rainfall_mm'].groupby(df['Year'])

year_summary.min()

In [ ]:
#max rainfall
year_summary = df['Rainfall_mm'].groupby(df['Year'])

year_summary.max()

In [ ]:
#For UrbanRural
UrbanRural_summary = df['Rainfall_mm'].groupby(df['UrbanRural'])

#total rainfall
UrbanRural_summary.sum()

In [ ]:
#min rainfall
UrbanRural_summary = df['Rainfall_mm'].groupby(df['UrbanRural'])

UrbanRural_summary.min()

In [ ]:
#max rainfall
UrbanRural_summary = df['Rainfall_mm'].groupby(df['UrbanRural'])

UrbanRural_summary.max()

6. For each **Region**, calculate the average temperature range per month (i.e., average of MaxTemp_C - MinTemp_C). (4 Marks)

In [ ]:

df['temp_range'] = (df['MaxTemp_C'] - df['MinTemp_C'])
avg_temp_range = df.groupby([df['Region']]).agg(range_per_month = ('temp_range', 'mean'))

avg_temp_range

## Part 3: Data Visualization (matplotlib) (40 Marks)

1. **Bar Chart:**  (8 Marks)
   - Plot total rainfall by region, colored by Urban/Rural.
   - Add value labels, gridlines, axis labels, title, and adjust bar width for clarity.

In [ ]:
import matplotlib.pyplot as plt

total_rainfall = df.groupby(['Region', 'UrbanRural'])['Rainfall_mm'].sum().reset_index()

#X-axis labels
x_labels = [f"{r} ({u})" for r, u in zip(total_rainfall['Region'], total_rainfall['UrbanRural'])]

# Colors by UrbanRural
colors = {'Urban': 'r', 'Rural': 'b'}
bar_colors = [colors[u] for u in total_rainfall['UrbanRural']]

# Step 2: Use lecture-style plot
fig, axes = plt.subplots(1, 1, figsize=(10, 6))  # only one axis

# Bar plot
axes.bar(x_labels, total_rainfall['Rainfall_mm'], color=bar_colors, alpha=0.8)

# Add labels and grid
axes.set_title("Total Rainfall by Region (Urban vs Rural)", fontsize=13)
axes.set_ylabel("Rainfall (mm)")
axes.set_xlabel("Region (Urban/Rural)")
axes.grid(axis='y', linestyle='--', alpha=0.7)

# Add value labels
for i, val in enumerate(total_rainfall['Rainfall_mm']):
    axes.text(i, val + 2, f"{val:.1f}", ha='center', fontsize=9)

plt.tight_layout()
plt.show()

2. **Grouped Bar Chart:**  (6 Marks)
   - Show average monthly rainfall for each station.
   - Use different colors for each station, include a legend, rotate x-tick labels, and increase figure size for readability.

In [ ]:
#Calculate average monthly rainfall for each station
rainfall_avg = df.groupby(['Month', 'Station'])['Rainfall_mm'].mean().unstack()

fig, ax = plt.subplots(figsize=(12, 6)) 

rainfall_avg.plot(kind='bar', ax=ax)

ax.set_title("Average Monthly Rainfall by Station", fontsize=14)
ax.set_ylabel("Rainfall (mm)")
ax.set_xlabel("Month")
ax.grid(axis='y', linestyle='--', alpha=0.7)
plt.xticks(rotation=0)  # Rotate x-tick labels for readability
ax.legend(title="Station")

plt.tight_layout()
plt.show()

3. **Line Plot:**  (6 Marks)
   - Show the trend of rainfall over months for at least two selected stations.
   - Use markers, dashed lines, highlight the month with maximum rainfall, and format the x-axis for months.

In [ ]:
import matplotlib.pyplot as plt

# Choose two stations
stations = ['StationA', 'StationB']

# Filter and compute monthly average rainfall
monthly = df[df['Station'].isin(stations)].groupby(['Month', 'Station'])['Rainfall_mm'].mean().unstack()

# Order months properly (optional but good)
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
monthly = monthly.reindex(months)

# Plot
fig, ax = plt.subplots(figsize=(10, 5))
monthly.plot(ax=ax, marker='o', linestyle='--')

# Highlight max rainfall month (just once, not per station)
max_month = monthly.max(axis=1).idxmax()
max_value = monthly.max(axis=1).max()
ax.axvline(max_month, color='gray', linestyle=':', alpha=0.5)
ax.text(max_month, max_value + 2, f"Max: {max_value:.1f} mm", ha='center', fontsize=9)

# Styling
ax.set_title("Rainfall Trend Over Months (Two Stations)")
ax.set_ylabel("Rainfall (mm)")
ax.set_xlabel("Month")
ax.grid(True, linestyle='--', alpha=0.5)
plt.xticks(rotation=0)
ax.legend(title="Station")

plt.tight_layout()
plt.show()

4. **Boxplot:**  (6 Marks)
   - Display rainfall distributions by region and by Urban/Rural.
   - Use custom box colors, highlight outliers, and set y-axis limits.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Set up figure and axes
fig, axes = plt.subplots(1, 2, figsize=(12, 6))

# Custom color palette
palette = {'North': '#87CEEB', 'South': '#FFA07A', 'East': '#98FB98', 'West': '#DDA0DD'}
urban_palette = {'Urban': '#6495ED', 'Rural': '#FF7F50'}

# --- Boxplot by Region ---
sns.boxplot(data=df, x='Region', y='Rainfall_mm', hue='Region', palette=palette, ax=axes[0],
            flierprops=dict(marker='o', markerfacecolor='red', markersize=6))  # Outliers style
axes[0].set_title("Rainfall Distribution by Region")
axes[0].set_ylabel("Rainfall (mm)")
axes[0].set_ylim(0, df['Rainfall_mm'].max() + 20)
axes[0].grid(axis='y', linestyle='--', alpha=0.5)

# --- Boxplot by Urban/Rural ---
sns.boxplot(data=df, x='UrbanRural', y='Rainfall_mm', hue='UrbanRural', palette=urban_palette, ax=axes[1],
            flierprops=dict(marker='x', markerfacecolor='darkred', markersize=6))  # Outliers style
axes[1].set_title("Rainfall Distribution by Urban/Rural")
axes[1].set_ylabel("Rainfall (mm)")
axes[1].set_ylim(0, df['Rainfall_mm'].max() + 20)
axes[1].grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

5. **Scatter Plot:**  (6 Marks)
   - Visualize the relationship between rainfall and maximum temperature, colored by region.
   - Add axis labels, legend, gridlines, and an appropriate title.

In [ ]:
#Write your code here

6. **Heatmap:**  
   - Create a heatmap showing mean monthly rainfall for each region (Month on x-axis, Region on y-axis).
   - Add color bar, axis labels, and title.

In [ ]:
#Write your code here

7. **Formatting (for all plots):** (8 Marks)
   - Use descriptive titles, axis labels, and legends.
   - Increase font size for readability.
   - Save each figure as an image file (`.png`).
   - Use `plt.tight_layout()` for proper spacing.

In [ ]:
#Write your code here

## Part 4: Bonus Tasks (15 Marks)

1. Annotate at least one plot with the value and label of the highest/lowest point. (5 Marks)

In [ ]:
#Write your code here

2. Create a **facet/grid plot** comparing rainfall trends by region and Urban/Rural status. (5 Marks)

In [ ]:
#Write your code here

3. Write a brief summary (in a Markdown cell) of your main insights from the data and visualizations. (5 Marks)

#Write your summary here